### PR TITLE
Updated /

### PR DESCRIPTION
**Pull request by rfblock**
Changed grid rendering, added sidebar

### CODE REVIEW

**Comment by cdknight** [comment]
Things we should do:
* [ ] Move the CSS to a separate file
* [ ] Make the sidebar/index part of a separate emote-rendering page - remove from base.html

**Comment by rfblock** [comment]
I can move the css but i have no clue how to jinja2 so gl with that
Btw fixes #9

**Comment by rfblock** [comment]
> Things we should do:
> 
> * [X]  Move the CSS to a separate file
> * [ ]  Make the sidebar/index part of a separate emote-rendering page - remove from base.html

**Comment by cdknight** [comment]
The other part is pretty insignificant/is going to get changed a bit anyway, so don't worry about it.

**Comment by cdknight** [comment]
Merged. Thanks!

**Pull request merged**
